// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbzeenozsmklyjfzdjjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iemVlbm96c21rbHlqZnpkampoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjY3NTQsImV4cCI6MjA2NjQ0Mjc1NH0.87-r-sw6XsqrimSCxHjgVXghmSr3XRyJtMnywR7T-PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);